#!/bin/sh

# Tests for test_render_rss() function.

# The MIT License (MIT)
#
# Copyright (c) 2016 Sunaina Pai
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

_import=yes . ./oyster 

site_dir="$TWORK/_site"
cache_dir="$TWORK/_cache"

test_render_rss()
{
    render_blog "$TDATA/dated-blog.in" "*.html" "" "/dated-blog.out"
    render_feed "$TDATA/dated-blog.in" 0 \
                "My Blog" "http://www.example.com/blog/" \
                "My thoughts on technology" \
                "/rss.xml"
    diff -u "$TDATA/rss.0.xml" "$site_dir/rss.xml"
}

test_render_rss_2()
{
    render_blog "$TDATA/dated-blog.in" "*.html" "" "/dated-blog.out"
    render_feed "$TDATA/dated-blog.in" 2 \
                "My Blog" "http://www.example.com/blog/" \
                "My thoughts on technology" \
                "/rss.xml"
    diff -u "$TDATA/rss.2.xml" "$site_dir/rss.xml"
}
