#!/bin/sh

# Tests for utility functions.

# The MIT License (MIT)
#
# Copyright (c) 2016 Sunaina Pai
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

_import=yes . ./oyster 

test_get_post_id()
{
    get_post_id 2016-08-09-hello-world.html |
    grep -q -F -x hello-world || return 1

    get_post_id hello-world.html |
    grep -q -F -x hello-world || return 1

    get_post_id /foo/bar/2016-08-09-hello-world.html |
    grep -q -F -x hello-world || return 1

    get_post_id /foo/bar/hello-world.html |
    grep -q -F -x hello-world || return 1

}

test_get_post_date()
{
    get_post_date 2016-08-09-hello-world.html |
    grep -q -F -x 2016-08-09 || return 1

    get_post_date /foo/bar/2016-08-09-hello-world.html |
    grep -q -F -x 2016-08-09 || return 1
}

test_get_post_year()
{
    get_post_year 2016-08-09-hello-world.html |
    grep -q -F -x 2016 || return 1

    get_post_year /foo/bar/2016-08-09-hello-world.html |
    grep -q -F -x 2016 || return 1
}

test_strip_html()
{
    echo "<p>Foo <a href="#1">Bar</a> Baz</p>" | strip_html |
    grep -q -F -x "Foo Bar Baz" || return 1
}

test_snip()
{
    echo "Foo Bar Baz Qux Foo Bar Baz Qux" | snip 4 |
    grep -q -F -x "Foo Bar Baz Qux" || return 1

    printf "Foo Bar\nBaz Qux\nFoo Bar\nBaz Qux\n" | snip 4 |
    grep -q -F -x "Foo Bar Baz Qux" || return 1
}
