#!/bin/sh

# Tests for render() function.

# The MIT License (MIT)
#
# Copyright (c) 2016 Sunaina Pai
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

_import=yes . ./oyster

CACHE_DIR="$TWORK/_cache"

test_out_string()
{
    out foo > "$TWORK/out.txt"
    diff -u "$TDATA/out1.out.txt" "$TWORK/out.txt"
}

test_out_strings()
{
    out "foo  bar" "baz  qux" > "$TWORK/out.txt"
    diff -u "$TDATA/out2.out.txt" "$TWORK/out.txt"
}

test_out_stdin()
{
    echo foo | out > "$TWORK/out.txt"
    diff -u "$TDATA/out1.out.txt" "$TWORK/out.txt"
}

test_remove_trailing_newlines()
{
    printf "\n\n\n   foo  bar\nbaz  qux   \n  \n\n\n" | out > "$TWORK/out.txt"
    diff -u "$TDATA/out3.out.txt" "$TWORK/out.txt"
}
