#!/bin/sh

# Tests for command line interface.

# The MIT License (MIT)
#
# Copyright (c) 2016 Sunaina Pai
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

_import=yes . ./oyster 

test_help()
{
    for opt in -h --help
    do
        _main $opt | head -n 1 | grep -q "^Usage:" || return 1
    done
}

test_version()
{
    for opt in -v --version
    do
        _main $opt | head -n 1 | grep -q "^.* $VERSION$" || return 1
    done
}

test_unknown_option()
{
    _main -x 2>&1 | grep -q '^.*: Unknown option "-x"\.$' || return 1
    _main --xyz 2>&1 | grep -q '^.*: Unknown option "--xyz"\.$' || return 1
}

test_surplus_argument()
{
    _main foo 2>&1 | grep -q '^.*: Surplus argument "foo"\.$'
}

test_no_args()
{
    cd "$TDATA/blank-site.in"
    _main | grep -q "^site configuration$" || return 1
    cd "$OLDPWD"
}

test_serve()
{
    cd "$TDATA/blank-site.in"
    _SERVE_COMMANDS="false${_NL}false${_NL}echo foo"
    _main --serve | grep -q foo || return 1
    cd "$OLDPWD"
}
