os:
    - linux
    - osx

install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo make install_kcov; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo make install_shells; fi

script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo make test_all; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo make test_unix; fi
