#!/bin/sh

# Oyster - Embedded shell based static blog generator

# The MIT License (MIT)
#
# Copyright (c) 2016 Sunaina Pai
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


VERSION=0.1.0-DEV
AUTHOR="Sunaina Pai"
COPYRIGHT="Copyright (c) 2016 $AUTHOR"
SUPPORT_URL="https://github.com/sunainapai/oyster/issues"
NAME=${0##*/}


# CORE AND UTILITY VARIABLES
# ==========================
# The following variables are used by core and utility functions. These
# variables may be altered in site configuration script to alter the
# behaviour of the core and utility functions.

# Directory location where the rendered pages are written to. This is
# known as the site root of the website.
SITE_DIR=_site

# Directory where cache files are written to. The cache files are used
# internally by this script to speed up certain rendering functions.
CACHE_DIR=_cache

# Length of blog post snippets. The length is specified in number of
# words. The render_blog function truncates each post it encounters to
# SNIP_LEN number of words and caches the truncated post snippet in snip
# cache. The snip cache can then be used to render blog index, i.e. a
# page with a list of recent blog posts or a page with an archive of all
# blog posts.
SNIP_LEN=25


# PRIVATE VARIABLES
# =================
# The following variables may be used by any function in the script.
# Do not modify these variables in site configuration script.

# Newline character.
_NL="
"


# CORE FUNCTIONS
# ==============
# The following core functions form the core API that may be invoked
# from the site configuration script (site.sh by default) to render a
# blog or website.


# DESCRIPTION
#   Read file, find and execute shell commands embedded in text and
#   replace each command with the standard output written by the
#   command. If the file uses a template, render it recursively such
#   that the 'content' command is replaced with the output of the file.
#   The output generated due to the last template processed is the
#   output of this function.
#
#   Limitation: This function may only be called from the site
#   configuration script. If a text being rendered invokes the render
#   function within embedded shell code, the behaviour is undefined.
#   This function must not be called from embedded shell code.
#
# OPERANDS
#   1. File to be rendered. (Optional)
#
# STDIN
#   The standard input is used as file if no file operand is specified.
#
# STDOUT
#   The rendered file is written to the standard output.
#
# STDERR
#   Any errors encountered while rendering are written to the standard
#   error.
#
# EXIT STATUS
#   0 If the file is rendered successfully.
#   1 If the rendering fails.
render()
{
    _p1_cache_file="$CACHE_DIR/render/$1/p1.txt"
    _p2_cache_file="$CACHE_DIR/render/$1/p2.txt"
    mkdir -p "$CACHE_DIR/render/$1"

    if [ -n "$1" ]
    then
        _eval_embedded_shell < "$1" > "$_p1_cache_file"
    else
        _eval_embedded_shell <<eof > "$_p1_cache_file"
$(cat)
eof
    fi

    # Copy P1 cache to P2 cache to ensure that P2 cache always contains
    # the rendered content after all passes, regardless the number of
    # passes, i.e. even when there is only pass.
    cp "$_p1_cache_file" "$_p2_cache_file"

    _content=$(cat "$_p2_cache_file")
    while [ -n "$_template" ]
    do
        _template_file=$_template
        # Store the file name to execute, unset _template so that it can
        # be defined afresh in next execution. If the next execution
        # does not define a template, _template variable remains unset
        # which ends the loop.
        unset _template
        _eval_embedded_shell < "$_template_file" > "$_p2_cache_file"
        _content=$(cat "$_p2_cache_file")
    done

    # Introduce new line at the end of file to overcome noeol.
    printf "%s\n" "$_content"

    unset _p1_cache_file
    unset _p2_cache_file
    unset _content
    unset _template_file
}


# Output cached rendered file after the first pass of rendering.
#
# When a file is rendered, it may undergo multiple passes of rendering.
# In the first pass, all embedded shell code in the file is rendered,
# but any template calls are not processed. This rendered file is cached
# in a location called p1 cache (p1 stands for the first pass).
#
# The template calls are processed in subsequent calls of rendering. The
# final rendered file is cached in a location called p2 cache (p2 stands
# for the second and subsequent passes). When there is no template call
# in the file, then the rendering is complete in the first pass itself.
# However, a p2 cache that is identical to p1 cache is created. This is
# created to ensure that one can always find the final rendered file in
# p2 cache regardless of the number of passes required to render the
# file.
#
# This function outputs the content of p1 cache that contains the
# rendered file without the file embedded in any template.
#
# OPERANDS
#   1. Path to the file that was rendered. If stdin was rendered, then
#      omit this operand to get p1 cache for rendered stdin.
#
# STDIN
#   Not used.
#
# STDOUT
#   The rendered file found in the p1 cache is written to the standard
#   output.
#
# STDERR
#   The standard error shall be used only for diagnostic messages.
#
# EXIT STATUS
#   0 Cached rendered file is output successfully.
#   1 An error occurred.
get_p1_cache()
{
    cat "$CACHE_DIR/render/$1/p1.txt"
}


# Output cached rendered file after all passes of rendering.
#
# See description of the get_p1_cache function to read about how a file
# may be rendered in multiple passes and the resulting p1 and p2 caches.
#
# This function outputs the content of p2 cache that contains the final
# rendered file.
#
# OPERANDS
#   1. Path to the file that was rendered. If stdin was rendered, then
#      omit this operand to get p1 cache for rendered stdin.
#
# STDIN
#   Not used.
#
# STDOUT
#   The rendered file found in the p2 cache is written to the standard
#   output.
#
# STDERR
#   The standard error shall be used only for diagnostic messages.
#
# EXIT STATUS
#   0 Cached rendered file is output successfully.
#   1 An error occurred.
get_p2_cache()
{
    cat "$CACHE_DIR/render/$1/p2.txt"
}


# DESCRIPTION
#   Set base template for a content file being rendered.
#
#   A content file is a file that invokes the 'template' command. The
#   filename specified as argument to the 'template' command is known as
#   the template file.
#
#   This function must be called with the path to the template file as
#   its argument. The path must be relative to the directory where
#   oyster is run.
#
#   Once this function is called in a content file, the template file
#   specified as the argument is considered to be the base template for
#   the content file. The files are rendered according to the following
#   algorithm.
#
#     1. The content file is rendered first.
#     2. If the content file does not invoke the 'template' function,
#        then rendering is complete. No further steps are performed.
#     3. If the content file invokes the 'template' function, then
#        the template file is rendered.
#     4. Any occurrence of the 'content' function call in the template
#        file is replaced with the rendered content file.
#     5. Now assume the template file to be content file and go to step 2.
#
#   Note that a template file itself may be a content file if it
#   invokes the 'template' command.
#
# OPERANDS
#   1. Path to the template file relative to where oyster is run.
#
# STDIN
#   Not used.
#
# STDOUT
#   Not used.
#
# STDERR
#   Not used.
#
# EXIT STATUS
#   0
template()
{
    _template=$1
}


# DESCRIPTION
#   Output rendered content file that invoked the current template file.
#
#   See the comments for the 'template' function for more details about
#   how the 'template' and 'content' functions work together.
#
# OPERANDS
#   None.
#
# STDIN
#   Not used.
#
# STDOUT
#   Not used.
#
# STDERR
#   Not used.
#
# EXIT STATUS
#   0
content()
{
    printf %s "$_content"
}


# DESCRIPTION
#   Render input text and include in the current text being rendered.
#   This function is similar to the render function with the following
#   exceptions:
#
#     1. This function may be called within embedded shell code.
#     2. This function ignores the template function call.
#
#   Therefore, this function cannot render any templates invoked within
#   embedded shell code.
#
# OPERANDS
#   1. File to be rendered. (Optional)
#
# STDIN
#   The standard input is used as file if no file operand is specified.
#
# STDOUT
#   The rendered file is written to the standard output.
#
# STDERR
#   Any errors encountered while rendering are written to the standard
#   error.
#
# EXIT STATUS
#   0 If the file is rendered successfully.
#   1 If the rendering fails.
include()
{
    if [ -n "$1" ]
    then
        _eval_embedded_shell < "$1"
    else
        _eval_embedded_shell <<eof
$(cat)
eof
    fi
}


# UTILITY FUNCTIONS
# =================
# The following utility functions form the utility API that may be
# invoked from the configuration script (site.sh by default).


# DESCRIPTION
#   Render a blog directory containing blog posts.
#
# OPERANDS
#   1. Path to source directory containing post files.
#   2. File pattern (glob) to search for post files.
#   3. Template to use to render files in source directory.
#      Use empty string, i.e. "", if a template is not to be used or if
#      the template is specified with template calls within the post
#      files.
#   4. Path relative to the site root of the website (SITE_DIR) where
#      the rendered blog is to be made available. The path should begin
#      with a forward slash, i.e. "/". If the path does not begin with a
#      forward slash, then a forward slash is added automatically at the
#      beginning before using the path, thus both "blog" and "/blog"
#      would behave equivalently, i.e. both would cause this function to
#      place the rendered blog posts at $SITE_DIR/blog/.
#
# STDIN
#   Not used.
#
# STDOUT
#   Progress details is written to the standard output.
#
# STDERR
#   Errors encountered while rendering is written to the standard error.
#
# EXIT STATUS
#   0 On success.
#   1 On failure.
render_blog()
{
    find "$1" -name "$2" |
    while read -r post_file
    do
        post_date=$(get_post_date "$post_file")
        post_id=$(get_post_id "$post_file")
        post_url="$4/$post_id/"

        printf %s "$post_url" | grep -q "^/" || post_url="/$post_url"

        post_create_date=$post_date

        # Create directory for post's index.html.
        mkdir -p "$SITE_DIR/$post_url/"

        # Write rendered post file.
        printf "%s\n" "Rendering $post_file ..."
        template "$3"
        unset post_title
        render "$post_file" > "$SITE_DIR$post_url/index.html"

        # Cache post snippet.
        get_p1_cache "$post_file" | strip_html | snip "$SNIP_LEN" > \
        "$CACHE_DIR/render/$post_file/snip.txt"

        # Update blog index cache.
        printf "%s\n" "$post_date:$post_url:$post_file:$post_title" >> \
        "$CACHE_DIR/render/$1/index.txt"

        unset post_date
        unset post_create_date
        unset post_id
        unset post_url
        unset post_file
    done
}


# DESCRIPTION
#   Output cached index of blog posts.
#
#   When render_blog function is used to render a directory of posts, an
#   index for all posts is created and cached. This index is a sequence
#   of lines with each line containing metadata about each post. Each
#   line is in the following format.
#
#     <date>:<url>:<filepath>:<title>
#
#   where
#
#     - <date> is the post creation date.
#     - <url> is the URL of the post relative to the site root.
#       <url> always begins with a forward slash.
#     - <filepath> is the path to the post file.
#     - <title> is the $post_title variable defined in the post file.
#
#   This function outputs this index in reverse sorted order, i.e. in
#   descending order of post creation dates. Therefore, newer posts
#   appear before older posts.
#
# OPERANDS
#   1. Path to source directory containing post files that were
#      rendered.
#
# STDIN
#   Not used.
#
# STDOUT
#   The index cache is written to the standard output in descending
#   order of post creation dates.
#
# STDERR
#   The standard error shall be used only for diagnostic messages.
#
# EXIT STATUS
#   0 On success.
#   1 On failure.
get_index_cache()
{
    sort -n -r "$CACHE_DIR/render/$1/index.txt"
}


# DESCRIPTION
#   Output post snippet cache.
#
#   When render_blog function is used to render a directory of posts, a
#   post snippet is created out of each post and cached. The post
#   snippet contains only the first SNIP_LEN number of words.
#
#   This function outputs post snippet for a specified post.
#
# OPERANDS
#   1. Path to a post file that was rendered.
#
# STDIN
#   Not used.
#
# STDOUT
#   The post snippet found in the cache is written to the standard
#   output.
#
# STDERR
#   The standard error shall be used only for diagnostic messages.
#
# EXIT STATUS
#   0 On success.
#   1 On failure.
get_snip_cache()
{
    cat "$CACHE_DIR/render/$1/snip.txt"
}


# DESCRIPTION
#   Output blog index as HTML.
#
#   When render_blog function is used to render a directory of posts, an
#   index for all posts is created and cached. This function outputs
#   this index cache in HTML format. This function may be invoked from
#   embedded shell code of any page that wants to display a list of blog
#   posts.
#
#   This function must be called for a directory of post files only
#   after render_blog has been called for the same directory.
#
# OPERANDS
#   1. Path to source directory containing post files.
#   2. Number of posts to render. If this operand is a positive integer,
#      then it indicates the number of posts to render. If this operand
#      is missing or if this operand is not a positive integer, then all
#      posts are rendered.
#   3. Whether to group posts by year. Specify "year" to group posts by
#      year. If this operand is missing or if this operand is not
#      "year", then the posts are not grouped by year.
#
# STDIN
#   Not used.
#
# STDOUT
#   The post snippet found in the cache is written to the standard
#   output in HTML format.
#
# STDERR
#   The standard error shall be used only for diagnostic messages.
#
# EXIT STATUS
#   0 On success.
#   1 On failure.
get_index_html()
{
    post_count=0

    get_index_cache "$1" |
    while IFS=: read -r post_date post_url post_file post_title
    do
        post_snip=$(get_snip_cache "$post_file")
        post_year=$(get_post_year "$post_file")

        if [ "$3" = year ] && [ "$prev_post_year" != "$post_year" ]
        then
            printf "<h2>%s</h2>\n<hr>\n" "$post_year"
            prev_post_year=$post_year
        fi

        printf "%s\n" "<h3><a href="$post_url">$post_title</a></h3>"
        printf "%s\n" "<p>$post_snip <a href="$post_url">...</a></p>"
        post_count=$(( $post_count + 1 ))
        [ $post_count = "$2" ] && break
    done

    unset post_count
    unset post_snip
    unset post_year
    unset prev_post_year
}


# DESCRIPTION
#   Extract post ID from post file path.
#
#   The syntax of a file name is [date-]title.ext,
#   e.g. 2016-08-09-hello-world.html, hello-world.html, etc.
#
#   This function removes any leading directory path, date, trailing
#   extension name and returns only the title part of the filename.
#
#   Examples:
#     get_post_id /foo/bar/2016-08-09-hello-world.html => hello-world
#     get_post_id /foo/bar/hello-world.html => hello-world
#
#   Only alphanumeric characters, underscore and hyphen are supported in
#   the filename. If any other characters are specified in the filename,
#   the behaviour is unspecified.
#
#   The post ID is used as post slug in the URL of the post when the
#   posts are rendered by the render_blog function.
#
# OPERANDS
#   1. Path to post file.
#
# STDIN
#   Not used.
#
# STDOUT
#   Post ID is written to the standard output.
#
# STDERR
#   Not used.
#
# EXIT STATUS
#   0 On success.
#   1 On failure.
get_post_id()
{
    # Remove leading directory path.
    set "${1##*/}"

    # Remove leading date.
    set "${1##[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]-}"

    # Remove trailing extension name.
    set "${1%%.*}"

    # Output the post ID.
    printf %s "$1"
}


# DESCRIPTION
#   Extract post date from post file path.
#
#   The filename must be in YYYY-MM-DD-title.ext format. If not, the
#   behaviour of this function is undefined.
#
#   Examples:
#     get_post_date /foo/bar/2016-08-09-hello-world.html => 2016-08-09
#     get_post_date /foo/bar/hello-world.html => Undefined behaviour
#
# OPERANDS
#   1. Path to post file.
#
# STDIN
#   Not used.
#
# STDOUT
#   Post date is written to the standard output.
#
# STDERR
#   Not used.
#
# EXIT STATUS
#   0 On success.
#   1 On failure.
get_post_date()
{
    printf %s "${1##*/}" | sed "s/.*\([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\).*/\1/"
}


# DESCRIPTION
#   Extract post year from post file path.
#
#   The filename must be in YYYY-MM-DD-title.ext format. If not, the
#   behaviour of this function is undefined.
#
#   Examples:
#     get_post_year /foo/bar/2016-08-09-hello-world.html => 2016
#     get_post_year /foo/bar/hello-world.html => Undefined behaviour
#
# OPERANDS
#   1. Path to post file.
#
# STDIN
#   Not used.
#
# STDOUT
#   Post year is written to the standard output.
#
# STDERR
#   Not used.
#
# EXIT STATUS
#   0 On success.
#   1 On failure.
get_post_year()
{
    # Remove leading directory path.
    set "${1##*/}"

    # Remove everything except year (YYYY).
    set "${1%-[0-9][0-9]-[0-9][0-9]-*}"

    # Output the post year.
    printf %s "$1"
}


# DESCRIPTION
#   Remove HTML tags from specified text.
#
# OPERANDS
#   1. Text with HTML tags.
#
# STDIN
#   None.
#
# STDOUT
#   Post year is written to the standard output.
#
# STDERR
#   Not used.
#
# EXIT STATUS
#   0 On success.
#   1 On failure.
strip_html()
{
    sed 's/<[^>]*>//g'
}


# DESCRIPTION
#   Truncate text to the specified number of words.
#
# OPERANDS
#   1. Number of words to truncate the given text to.
#
# STDIN
#   Input text.
#
# STDOUT
#   Post year is written to the standard output.
#
# STDERR
#   Not used.
#
# EXIT STATUS
#   0 On success.
#   1 On failure.
snip()
{
    # Follow each word with a space and newline.
    sed "s/$/ /" | sed "s/ / \\$_NL/g" |

    # Ignore lines consisting only of whitespace and non-printable
    # characters.
    grep "[[:graph:]]" |

    # Select the specified number of lines.
    head -n "$1" |

    # Remove the newlines.
    tr -d '\n' |

    # Replace the trailing space with a newline.
    sed "s/ $/\\$_NL/"
}


# PRIVATE FUNCTIONS
# =================
# The following private functions are not part of the API. They should
# not be invoked directly by the configuration script.


# DESCRIPTION
#   Find shell code embedded in the input text, evaluate the shell
#   commands and replace the shell code with their output.
#
#   The input text is tokenized into two kinds of text:
#
#     1. Shell code delimited with shell code tags (default: '{{' and '}}').
#     2. Static text, i.e. any text that is not shell code.
#
#   Each block of shell code is executed and the block is replaced with
#   the standard output generated the shell code.
#
# OPERANDS
#   None.
#
# STDIN
#   The standard input is used as the file to be rendered.
#
# STDOUT
#   The rendered file is written to the standard output.
#
# STDERR
#   Any errors encountered while rendering are written to the standard
#   error.
#
# EXIT STATUS
#   0 If the file is rendered successfully.
#   1 If the rendering fails.
_eval_embedded_shell()
{
    while IFS= read -r _line
    do
        # Tokenize input: For each line in the input file, place each
        # occurrence of shell code, e.g. "{{ date }}", on its own line.
        # Each output line contains a single token (i.e. static text or
        # shell code). These lines of tokens are fed to the inner while
        # loop.
        #
        # Note: The three statements below could have been written as a
        # single pipeline. But they are written as separate statements
        # to work around a kcov bug; kcov misses all lines except the
        # last one in a multiline command substitution.
        tokens=$(printf %s "$_line")
        tokens=$(printf %s "$tokens" | sed "s/{{/\\$_NL{{/g")
        tokens=$(printf %s "$tokens" | sed "s/}}/}}\\$_NL/g")

        # Loop over the each line of tokenized input and evaluate the
        # shell-script-tokens.
        # Set IFS to nothing, to preserve indentation, whitespaces etc.
        while IFS= read -r _token
        do
            if printf "%s" "$_token" | grep -q "^{{"
            then
                # While tokenizing, we inserted a newline before each
                # shell script token. We undo that by printing the
                # output of the evaluated shell script without any
                # preceding newline.
                _code=$(printf "%s" "$_token" | sed "s/.*{{\(.*\)}}.*/\1/")
                eval "$_code"
            else
                printf "%s" "$_token"
            fi

# Do not indent anything within here-document to workaround a yash bug
# where read command does not remove leading IFS. Ensure that input to
# read command does not contain leading IFS.
        done <<eof
$(printf %s "$tokens")
eof
        # Write a new line as we have reached the end of the original source
        # code line.
        printf "\n"
        done

    unset _code
    unset _line
    unset _token
}


# DESCRIPTION
#   Starting point of this script.
#
# OPERANDS
#   All command line arguments this script was invoked with.
#
# STDIN
#   Not used.
#
# STDOUT
#   Output of some command line arguments such as -h/--help,
#   -v/--version, etc. are written to the standard output.
#
# STDERR
#   Any errors encountered while processing command line arguments or
#   while rendering files are written to the standard error.
#
# EXIT STATUS
#   0 If the script completes running successfully.
#   1 If there is a failure.
_main()
{
    _parse_arguments "$@"
    _build_site
    if [ "$_serve" = yes ]
    then
        _serve_site
    fi
}


# DESCRIPTION
#   Parse command line arguments passed to this script.
#
# OPERANDS
#   All command line arguments this script was invoked with.
#
# STDIN
#   Not used.
#
# STDOUT
#   Output of some command line arguments such as -h/--help,
#   -v/--version, etc. are written to the standard output.
#
# STDERR
#   Any errors encountered while processing command line arguments or
#   while rendering files are written to the standard error.
#
# EXIT STATUS
#   0 If the command line arguments are parsed and processed successfully.
#   1 If unknown command line option or argument is encountered.
_parse_arguments()
{
    while [ $# -gt 0 ]
    do
        case $1 in
            -h | --help)
                _show_help
                exit
                ;;
            -v | --version)
                _show_version
                exit
                ;;
            -s | --serve)
                _serve=yes
                shift
                ;;
            -*)
                quit Unknown option \""$1"\".
                ;;
            *)
                quit Surplus argument \""$1"\".
                ;;
        esac
    done
}


# DESCRIPTION
#   Show help.
#
# OPERANDS
#   None.
#
# STDIN
#   Not used.
#
# STDOUT
#   Usage details is written to the standard output.
#
# STDERR
#   Not used.
#
# EXIT STATUS
#   0
_show_help()
{
    cat <<eof
Usage: $NAME [-s] [-h] [-v]

Render static website. A site configuration script (default: ./site.sh)
is executed to render the website. It is the responsibility of the site
configuration script to call the oyster API to render the site source
files and write the rendered files into the site output directory.

Options:
  -s, --serve    Serve site with Python HTTP server.
  -h, --help     Display this help and exit.
  -v, --version  Display version information and exit.

Report bugs to <$SUPPORT_URL>.
eof
}


# DESCRIPTION
#   Show version and copyright.
#
# OPERANDS
#   None.
#
# STDIN
#   Not used.
#
# STDOUT
#   Version and copyright details are written to the standard output.
#
# STDERR
#   Not used.
#
# EXIT STATUS
#   0
_show_version()
{
    cat <<eof
Oyster $VERSION
$COPYRIGHT

This is free and open source software. You can use, copy, modify,
merge, publish, distribute, sublicense, and/or sell copies of it,
under the terms of the MIT License.

This software is provided "AS IS", WITHOUT WARRANTY OF ANY KIND,
express or implied. See the MIT License for details.
eof
}


# DESCRIPTION
#   Terminate the script with an error message.
#
# OPERANDS
#   The strings to be written as error message to the standard error.
#   An arbitrary number of string arguments may be specified. All
#   arguments are joined into a single error message with spaces
#   introduced between arguments.
#
# STDIN
#   Not used.
#
# STDOUT
#   Not used.
#
# STDERR
#   Error message is written to the standard error.
#
# EXIT STATUS
#   1
quit()
{
    printf "%s: %s\n" "$NAME" "$*" >&2
    exit 1
}


# DESCRIPTION
#   Build website in current directory.
#
#   This function merely executes a site configuration script (./site.sh
#   by default). It is the responsibility of the site configuration
#   script to invoke the oyster API to build the site and write the
#   rendered files into a site output directory.
#
# OPERANDS
#   None.
#
# STDIN
#   Not used.
#
# STDOUT
#   Site configuration script's standard output is going to be written here.
#
# STDERR
#   Site configuration script's standard error is going to be written here.
#
# EXIT STATUS
#   0 On success.
#   1 On failure.
_build_site()
{
    . ./site.sh
}


# Commands to try to serve generated website.
#
# Each command is specified in a separate line. Each command is tried in
# the order specified until a command exits with status code 0.
_SERVE_COMMANDS="$(cat <<eof
python3 -c "import http.server" 2> /dev/null && python3 -m http.server
python -c "import http.server" 2> /dev/null && python -m http.server
python -c "import SimpleHTTPServer" 2> /dev/null && python -m SimpleHTTPServer
eof
)"


# DESCRIPTION
#   Serve generated website using Python's HTTP server.
#
#   This function assumes that the generated website is rendered within
#   _site directory relative to the current directory.
#
# OPERANDS
#   None.
#
# STDIN
#   Not used.
#
# STDOUT
#   Python HTTP server's standard output is going to be written here.
#
# STDERR
#   Python HTTP server's standard error is going to be written here.
#
# EXIT STATUS
#   0 On success.
#   1 On failure.
_serve_site()
{
    cd "$SITE_DIR" || quit Cannot find site directory.

    printf "%s\n" "$_SERVE_COMMANDS" | while read -r _command
    do
        printf "Trying %s ...\n" "$_command"
        eval "$_command" && break
    done
}


# Test files set _import=yes to prevent _main() from executing.
[ "$_import" = yes ] || _main "$@"
